spring.datasource.url=jdbc:postgresql://localhost:5432/idecttDb
spring.datasource.username=postgres
spring.datasource.password=131313
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
idectt.app.jwtSecret=YourSuperSecretKeyForJWTGenerationAndValidationWhichShouldBeAtLeast256BitsLong
# 24 hours
idectt.app.jwtExpirationMs=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
