spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/idecttDb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:131313}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
idectt.app.jwtSecret=${JWT_SECRET:YourSuperSecretKeyForJWTGenerationAndValidationWhichShouldBeAtLeast256BitsLong}
# 24 hours
idectt.app.jwtExpirationMs=86400000

# CORS Configuration
idectt.app.cors.allowedOrigins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://51.20.56.7,https://www.kyddtr.com,https://kyddtr.com}

# File Upload Configuration
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
